#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    entities:
        # List the entity class name you want to manage
        Destination:
            class: App\Entity\Destination
        ClassGroup:
            class: App\Entity\ClassGroup
        Note:
            class: App\Entity\Note
        Project:
            class: App\Entity\Project
        Role:
            class: App\Entity\Role
        Tag:
            class: App\Entity\Tag
        User:
            class: App\Entity\User