#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Destination
        - App\Entity\Group
        - App\Entity\Note
        - App\Entity\Project
        - App\Entity\Role
        - App\Entity\Tag
        - App\Entity\User